export class DiagnosisEntity {
  id!: number;
  userId!: number;
  userName!: string;
  userEmail!: string;
  cropId!: number | null;
  cropName!: string;
  imageUrl!: string | null;
  imageName!: string | null;
  fieldNotes!: string | null;
  diseaseName!: string;
  confidence!: number;
  recommendation!: string;
  summary!: string;
  medicineName!: string;
  applicationRate!: string;
  preventionPlan!: string;
  severity!: 'low' | 'medium' | 'high';
  urgency!: 'monitor' | 'soon' | 'immediate';
  suspectedConditions!: string[];
  nextSteps!: string[];
  knowledgeMatches!: string[];
  advisorySource!: 'knowledge-guided-openai' | 'knowledge-guided-mock';
  reviewStatus!: 'pending' | 'reviewed' | 'escalated';
  reviewedByName!: string | null;
  reviewNotes!: string | null;
  reviewedAt!: Date | null;
  provider!: 'openai' | 'mock';
  model!: string;
  createdAt!: Date;
}
